package solutions;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 *  Input:
 *  s = "abcd"
 *  t = "abcde"
 *
 *  Output:
 *  e
 *
 * Explanation:
 *  'e' is the letter that was added.
 */

public class Q389 extends Solution {

    public char findTheDifference(String s, String t) {
        int[] table = new int[26];
        char[] sChars = s.toCharArray(), tChars = t.toCharArray();
        for (int i = 0; i < sChars.length; ++i) {
            table[sChars[i] - 'a']--;
            table[tChars[i] - 'a']++;
        }
        table[tChars[tChars.length - 1] - 'a']++;
        for (int i = 0; i < table.length; ++i) {
            if (table[i] == 1) {
                return (char)('a' + i);
            }
        }
        return ' ';
    }

}
